### ISSUE TITLE
XML schematron validation

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/libsbgn-python#11]
I could not get the schematron validation working with python so far.
I tried the XSLT transformation approach and directly using lxml schematron.

Schema can be transformed, but validation results in 
```
Traceback (most recent call last):
  File "/home/mkoenig/git/libsbgn-python/libsbgnpy/validation/validator.py", line 141, in <module>
    sct_valid = validate_schematron(f)
  File "/home/mkoenig/git/libsbgn-python/libsbgnpy/validation/validator.py", line 123, in validate_schematron
    doc_svrlt = transform_2(doc_sbgn)
  File "src/lxml/xslt.pxi", line 599, in lxml.etree.XSLT.__call__ (src/lxml/lxml.etree.c:175596)
lxml.etree.XSLTApplyError: Failed to evaluate the expression of variable 'arc-count-distinct-1'.
```

**Comment by matthiaskoenig** [comment]
Not doing this.
