### ISSUE TITLE
ConnectionError "sysbioapps.dyndns.org" when rendering an SBGN.

### ISSUE THREAD

**Issue by lhannest** [matthiaskoenig/libsbgn-python#31]
Executing this code from the [documentation](https://libsbgn-python.readthedocs.io/en/latest/examples.html#Render-SBGN):
```
from libsbgnpy import render, utils
import tempfile

sbgn = utils.read_from_file("backend/data/sbgn/R-HSA-15869.sbgn")
f_png = tempfile.NamedTemporaryFile(suffix=".png")
render.render_sbgn(sbgn, image_file=f_png.name,
                   file_format="png")
Image(f_png.name, width=500)
```
Getting this exception:
```
Traceback (most recent call last):
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ffae01fb080>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='sysbioapps.dyndns.org', port=80): Max retries exceeded with url: /Layout/GenerateImage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffae01fb080>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    file_format="png")
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/libsbgnpy/render.py", line 44, in render_sbgn
    r = requests.post('http://sysbioapps.dyndns.org/Layout/GenerateImage', files=files)
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/lance/git/2019/April/biomed-workbench2/venv/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sysbioapps.dyndns.org', port=80): Max retries exceeded with url: /Layout/GenerateImage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffae01fb080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by matthiaskoenig** [comment]
Sorry, totally overlooked this issue.
The url changed to http://sysbioapps.spdns.org/Layout
I will commit a bugfix soon.
